name: Auto-update gifts.json from API

on:
  schedule:
    - cron: "* * * * *" # каждая минута
  workflow_dispatch: # возможность вручную запустить

jobs:
  update-gifts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download latest gifts.json from API
        run: |
          echo "Fetching data from API..."
          curl -s https://wishlist-minceraft.onrender.com/api/gifts -o new_gifts.json

      - name: Compare with existing file and update if needed
        run: |
          if ! cmp -s new_gifts.json gifts.json; then
            echo "Changes detected. Updating gifts.json..."
            mv new_gifts.json gifts.json
            git config user.name "GitHub Action"
            git config user.email "actions@github.com"
            git add gifts.json
            git commit -m "Auto-update gifts.json from API [skip ci]"
            git push
          else
            echo "No changes detected."
          fi
